---
title: "Mono Lake Levels Data Viusalization"
author: "Anastasia Kunz"
date: "12/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(here)
library(janitor)
library(tidyverse)
library(lubridate)
library(gganimate)
```

```{r}
#read in data
mono_lake <- read_csv(here("data", "mono_lake_annual_levels.csv"), skip = 5)
```

```{r}
# simplify dataset, rename some varibales 
mono_levels <- mono_lake %>% 
  clean_names() %>% 
  rename(level = lake_level_feet_above_sea_level)
 
  

```

```{r}
# Data Vis here
ggplot(mono_levels, aes(x = year, y = level))+
  geom_line(size = .8, color = "dodgerblue2", alpha = .6)+
   geom_ribbon(aes(ymin = -Inf,
                  ymax = level),
              fill = "dodgerblue2",
              alpha = .15) +
  theme_bw()+
  labs(
    x = "Year",
    y = "Lake Level (Feet Above Sealevel)",
    title = "Time Series of Mono Lake Levels",
    subtitle = "1850 - 2017"
  )+
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.line = element_line(colour = "black"),
        panel.border = element_blank())+
  geom_hline(yintercept = 6350, size = .8, alpha = 0.6, color = "firebrick")+
  geom_hline(yintercept = 6360, size = .8, alpha = 0.6,color = "tomato")+
  geom_hline(yintercept = 6377, size = .8, alpha = 0.6,color = "orange")+
  geom_hline(yintercept = 6392, size = .8, alpha = 0.6,color = "deepskyblue4")+
  annotate(geom="text", x= 1869, y= 6394, size = 3.3, 
           label="Target level (6392 ft)")+
  annotate(geom = "text", x = 1874, y = 6379, size = 3.3,
          label = "Land bridge forms (6377 ft)")+
  annotate(geom = "text", x = 1878, y = 6362, size = 3.3,
           label = "Adverse salinity effects (6360 ft)")+
  annotate(geom = "text", x = 1883, y = 6352, size = 3.3,
           label = "Acute adverse salinity effects (6350 ft)")+
  
  annotate(geom = "point", x = 1940, y = 6417, size = 1.7, shape = 16, color = "mediumblue")+ 
  annotate(geom = "text", x = 1940, y = 6447, size = 3,
             label = 'atop(bold("1940"),"LA begins diverting water")', parse = TRUE)+
  annotate("segment", x = 1940, xend = 1940, y = 6417, yend = 6440, colour = "mediumblue", size=.4, alpha = .2)+
  
  annotate(geom = "text", x = 1979, y = 6440, size = 3,
             label = 'atop(bold("1979"),"Public Trust lawsuit")', parse = TRUE)+
  annotate(geom = "point", x = 1979, y = 6373.4, size = 1.7, shape = 16, color = "mediumblue")+
    annotate("segment", x = 1979, xend = 1979, y = 6373, yend = 6432, colour = "mediumblue", size=.4, alpha = .2)+
  
  annotate(geom = "point", x = 1983, y = 6378.6, size = 1.7, shape = 16, color = "mediumblue")+
   annotate(geom = "text", x = 1983, y = 6415, size = 3,
             label = 'atop(bold("1983"),"Supreme Court Decision")', parse = TRUE)+
  annotate("segment", x = 1983, xend = 1983, y = 6378, yend = 6409, colour = "mediumblue", size=.4, alpha = .2)+
  
  annotate(geom = "point", x = 1994, y = 6374.6, size = 1.7, shape = 16, color = "mediumblue")+
  annotate(geom = "text", x = 1994, y = 6400, size = 3,
             label = 'atop(bold("1994"),"State Water Board Decision")', parse = TRUE)+
  annotate("segment", x = 1994, xend = 1994, y = 6374, yend = 6394, colour = "mediumblue", size=.4, alpha = .2)+
    scale_x_continuous(limits = c(1850, 2017), 
                     breaks = c(1850, 1875, 1900, 1925, 1950, 1975, 2000, 2017),
                     expand = c(0, 0))

 
 
  
  
  

```

**Figure 1.** Caption here. Data: 



